### ISSUE TITLE
must pull before pusing

### ISSUE THREAD

**Issue by HoboChen** [xjtuacm/board#1]
some blob files are missing
and there are only 1 commit at xjtuacm.github.io

**Comment by zccz14** [comment]
or the pushing will be rejected

**Comment by HoboChen** [comment]
@zccz14 can use `git push -f`, but dangerous; i wonder if someone used it

**Comment by zccz14** [comment]
@HoboChen Force push to xjtuacm.github.io? so what? Did I misunderstand something?
