### ISSUE TITLE
Repo Clean Up Needed

### ISSUE THREAD

**Issue by HoboChen** [xjtuacm/board#10]
This is the public repo of XJTU ACM, so to put the standard code library of particular team is not recommended. Better solution is to put in the team leader and set the collaborators.

So, @sylxjtu @zccz14 could you spare some time migrate it?

Also, can we remove the board-old? @zccz14 

I am going to remove XJTUOJ-NULL.

**Comment by zccz14** [comment]
well, 我觉得板子可以保留在这里，可以促进板子间的交流

关于 board-old 这个 repo 我也没有印象了，而且里面确实没有什么东西，可以删除。

**Comment by HoboChen** [comment]
I cant see the chance of make it more difficult to share the scl if we migrate the scl repo to someone's github. Also, the two scl repo are poorly maintained.
I am going to delete the board-old.

**Comment by sylxjtu** [comment]
I'm going to transfer wellgasa-snippets to @zccz14 , and bitset-snippets to me.

UPD: Seems repos can only be transfered to a user himself, so @zccz14 please transfer wellgasa-snippets to yourself.

**Comment by HoboChen** [comment]
Closed
