### ISSUE TITLE
board 信息填补

### ISSUE THREAD

**Issue by HoboChen** [xjtuacm/board#3]
1. 在source内增加了/honor/index.md，请将静态链接放到主页
@zccz14 
2. /about/index.md增加了目录，请填补有关内容
@sylxjtu @igoodvegetablea 
3. 将www.xjtuacm.com解析到静态网页，网页中有两个链接分别指向board和oj
@zccz14 @sylxjtu

**Comment by zccz14** [comment]
@HoboChen 第一个做完了

第三个里面 www.xjtuacm.com 要解析到哪里？

**Comment by HoboChen** [comment]
解析到某个服务器的静态网页就好。。静态网页里面放链接到oj和board吧。。类似与一个网址导航？ @zccz14
